# Generated by Django 6.0.3 on 2026-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sysadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
