# Generated by Django 6.0.3 on 2026-03-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VietGAPRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('vietgap', 'VietGAP'), ('gacc', 'GACC')], max_length=20)),
                ('region_code', models.CharField(blank=True, max_length=100, null=True)),
                ('document_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Đang thẩm định'), ('approved', 'Đã cấp mã'), ('rejected', 'Cần bổ sung')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='api.admin')),
            ],
            options={
                'db_table': 'vietgap_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
