# Generated by Django 6.0.3 on 2026-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vietgapregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingzone',
            name='certificate_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
