# Generated by Django 6.0.3 on 2026-04-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plantingzone_certificate_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_crop_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_info', to='api.admin')),
            ],
            options={
                'db_table': 'farms',
                'ordering': ['-created_at'],
            },
        ),
    ]
