# Generated by Django. Add migration for Material status field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_plantingzone_certificate_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="status",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("active", "Cho phép sử dụng"),
                    ("inactive", "Hạn chế sử dụng"),
                    ("banned", "Cấm sử dụng"),
                ],
                default="active",
            ),
        ),
    ]
