# Generated by Django 6.0.3 on 2026-04-03 05:35

from django.db import migrations


def create_sample_farm_data(apps, schema_editor):
    """Create sample farm data for testing"""
    Farm = apps.get_model('api', 'Farm')
    Admin = apps.get_model('api', 'Admin')

    # Get existing admins or create sample ones
    admins = Admin.objects.all()
    if not admins.exists():
        # Create sample admin if none exist
        sample_admin = Admin.objects.create(
            name="HTX Nông nghiệp Xanh",
            phone="0987654321",
            address="Xã Liêm Tuyền, Huyện Thanh Trì, Hà Nội",
            representative="Nguyễn Văn An",
            registration_certificate="HTX-2024-001"
        )
        admins = [sample_admin]

    # Create sample farm data for each admin
    sample_farms = [
        {
            'admin': admins[0],
            'cooperative_name': 'HTX Nông nghiệp Xanh',
            'address': 'Thôn Đông Anh, Xã Liêm Tuyền, Huyện Thanh Trì, Thành phố Hà Nội',
            'total_area': 45.5,
            'main_crop_type': 'Rau'
        }
    ]

    # Add more sample farms if there are more admins
    if len(admins) > 1:
        sample_farms.append({
            'admin': admins[1],
            'cooperative_name': 'HTX Rau sạch Việt Nam',
            'address': 'Thôn Phú Mỹ, Xã Mỹ Hưng, Huyện Thanh Trì, Thành phố Hà Nội',
            'total_area': 32.8,
            'main_crop_type': 'Rau'
        })

    if len(admins) > 2:
        sample_farms.append({
            'admin': admins[2],
            'cooperative_name': 'HTX Lúa hữu cơ Bắc Bộ',
            'address': 'Thôn Trung Kiên, Xã Tả Thanh Oai, Huyện Thanh Trì, Thành phố Hà Nội',
            'total_area': 78.2,
            'main_crop_type': 'Lúa'
        })

    # Create farms, skip if already exists
    for farm_data in sample_farms:
        try:
            Farm.objects.get_or_create(
                admin=farm_data['admin'],
                defaults={
                    'cooperative_name': farm_data['cooperative_name'],
                    'address': farm_data['address'],
                    'total_area': farm_data['total_area'],
                    'main_crop_type': farm_data['main_crop_type']
                }
            )
        except Exception as e:
            print(f"Could not create farm for admin {farm_data['admin'].name}: {e}")


def reverse_sample_farm_data(apps, schema_editor):
    """Remove sample farm data"""
    Farm = apps.get_model('api', 'Farm')
    # Remove sample farms
    Farm.objects.filter(
        cooperative_name__in=[
            'HTX Nông nghiệp Xanh',
            'HTX Rau sạch Việt Nam',
            'HTX Lúa hữu cơ Bắc Bộ'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_farm'),
    ]

    operations = [
        migrations.RunPython(
            create_sample_farm_data,
            reverse_code=reverse_sample_farm_data
        )
    ]
