# Generated by Django 6.0.3 on 2026-04-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sample_farm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='admin',
            field=models.ForeignKey(
                default=1,
                help_text='Hợp tác xã mà nông dân thuộc về',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='farmers',
                to='api.admin'
            ),
        ),
    ]
