# Generated by Django 6.0.3 on 2026-04-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_material_status'),
        ('api', '0009_add_admin_to_farmer'),
    ]

    operations = [
    ]
