# Generated by Django 6.0.3 on 2026-04-04 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.admin'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='api.admin'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Hợp tác xã mà nông dân thuộc về', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='api.admin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('admin', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcategory',
            unique_together={('admin', 'name')},
        ),
    ]
