# Generated by Django 6.0.3 on 2026-04-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_default_tasks_to_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_name', models.CharField(max_length=50, unique=True)),
                ('color_variants', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_icons',
                'ordering': ['name'],
            },
        ),
        # Seed default icons
        migrations.RunPython(
            code=lambda apps, schema_editor: _seed_task_icons(apps),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]


def _seed_task_icons(apps):
    TaskIcon = apps.get_model('api', 'TaskIcon')
    
    icons_data = [
        {
            'name': 'Rửa vườn',
            'icon_name': 'Droplets',
            'color_variants': ['bg-blue-100 text-blue-600'],
            'description': 'Rửa vườn với nước'
        },
        {
            'name': 'Cắt tỉa cành',
            'icon_name': 'Scissors',
            'color_variants': ['bg-gray-100 text-gray-600'],
            'description': 'Cắt tỉa cành cây'
        },
        {
            'name': 'Làm sạch cỏ',
            'icon_name': 'Leaf',
            'color_variants': ['bg-green-100 text-green-600'],
            'description': 'Làm sạch cỏ dại'
        },
        {
            'name': 'Tưới nước',
            'icon_name': 'CloudRain',
            'color_variants': ['bg-cyan-100 text-cyan-600'],
            'description': 'Tưới nước cho cây'
        },
        {
            'name': 'Bón phân vi sinh',
            'icon_name': 'Sprout',
            'color_variants': ['bg-lime-100 text-lime-600'],
            'description': 'Bón phân vi sinh'
        },
        {
            'name': 'Bón phân',
            'icon_name': 'FlaskConical',
            'color_variants': ['bg-orange-100 text-orange-600', 'bg-amber-100 text-amber-600'],
            'description': 'Bón phân hóa học'
        },
        {
            'name': 'Phun sâu/rầy',
            'icon_name': 'BugOff',
            'color_variants': ['bg-red-100 text-red-600', 'bg-rose-100 text-rose-600'],
            'description': 'Phun thuốc sâu/rầy'
        },
        {
            'name': 'Phun nhện đỏ',
            'icon_name': 'SprayCan',
            'color_variants': ['bg-purple-100 text-purple-600'],
            'description': 'Phun thuốc nhện đỏ'
        },
        {
            'name': 'Đổ gốc',
            'icon_name': 'TreePine',
            'color_variants': ['bg-emerald-100 text-emerald-600'],
            'description': 'Đổ gốc cây'
        },
        {
            'name': 'Xử lý chất thải',
            'icon_name': 'Trash2',
            'color_variants': ['bg-stone-100 text-stone-600'],
            'description': 'Xử lý chất thải độc hại'
        },
        {
            'name': 'Quản lý vật tư',
            'icon_name': 'Package',
            'color_variants': ['bg-indigo-100 text-indigo-600'],
            'description': 'Quản lý vật tư'
        },
        {
            'name': 'Vệ sinh kho',
            'icon_name': 'Warehouse',
            'color_variants': ['bg-teal-100 text-teal-600'],
            'description': 'Vệ sinh kho bảo quản'
        },
        {
            'name': 'An toàn lao động',
            'icon_name': 'HardHat',
            'color_variants': ['bg-yellow-100 text-yellow-600'],
            'description': 'An toàn lao động'
        },
    ]
    
    for icon_data in icons_data:
        TaskIcon.objects.get_or_create(
            icon_name=icon_data['icon_name'],
            defaults=icon_data
        )
